""
"" UI
""
set guifont=Source\ Code\ Pro\ Light:h13 " font

colors liquidcarbon " Alternatives themes vilight / jellybeans / myste / codeschool / mustang

set guioptions-=r " Removes right hand scroll bar
set guioptions-=L " Removes left hand scroll bar

set guioptions-=m " remove menu bar
set guioptions-=T " remove toolbar

" set cursor properties
highlight Cursor guifg=white guibg=steelblue
highlight iCursor guifg=white guibg=steelblue
set gcr=n-c-v:hor10-Cursor-blinkon0
set gcr=i:ver15-Cursor-blinkwait600-blinkon1600-blinkoff800
:hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
" :hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
" :nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>
:nnoremap <Leader>c :set cursorline!<CR>
